### ISSUE TITLE
如果未定位情况下暂停跑步，应用将崩溃

### ISSUE THREAD

**Issue by owen8877** [pku-runner/pku-runner.github.io#11]
- 客户端平台：Android
- 客户端版本：v0.9.13
- 客户端下载渠道：未知
- 问题描述
  + 触发场景：跑步开始，出于未定位状态，点击暂停按钮
  + 预期结果：切换到暂停状态
  + 实际结果：应用崩溃

**Comment by castor-v-pollux** [comment]
描述的补充：
跑步开始，gps精度检测通过后信号中断，若此时点击暂停按钮导致崩溃；若此时点击结束按钮，可以正常结束，但点击跑步记录进入详情页时崩溃。

**Comment by castor-v-pollux** [comment]
已修复，下一次更新时生效。
