### ISSUE TITLE
F**k u damnit PKU Runner team

### ISSUE THREAD

**Issue by BlueFlo0d** [pku-runner/pku-runner.github.io#14]
The source code isn't released properly. WHAT IS the crapping in the "Source Code" tarball???

**Comment by owen8877** [comment]
Please read the [guidelines](https://github.com/pku-runner/pku-runner.github.io/blob/master/CONTRIBUTING.md) and [wiki page](https://github.com/pku-runner/pku-runner.github.io/wiki) first.

And as a matter of fact, we have released the source code of **[pkurunner/pku-runner.github.io](https://github.com/pku-runner/pku-runner.github.io)** quite properly.

**Comment by BlueFlo0d** [comment]
I could only find Android/iOS binary releases. WHERE IS the source code? Could you please provide a link? Most places which source code ought to lie in are documentations, such as the main repo and src Tarball, and I could not find the source anywhere.

**Comment by BlueFlo0d** [comment]
Well sorry I've realized that this is the source of the WEBSITE. However is the PKU Runner application open source?

**Comment by owen8877** [comment]
@BlueFlo0d Please read the [wiki page](https://github.com/pku-runner/pku-runner.github.io/wiki/PKU-Runner-Android-%E5%AE%A2%E6%88%B7%E7%AB%AF) carefully.
