### ISSUE TITLE
该安装包未包含任何证书

### ISSUE THREAD

**Issue by Firestar-Reimu** [pku-runner/pku-runner.github.io#25]
![微信图片_20210811013022](https://user-images.githubusercontent.com/65082432/128907227-74232768-7555-4abc-bc9c-de6899c4c5d9.jpg)

安卓版，7.31更新的

**Comment by 1900011604** [comment]
8.11更新：没问题了

**Comment by 1900011604** [comment]
8.11更新，没问题了
