### ISSUE TITLE
PKU Runner 招新帖

### ISSUE THREAD

**Issue by owen8877** [pku-runner/pku-runner.github.io#7]
### 前情提要
经过两个学期的努力，PKU Runner <del>终于</del> 马上就要上线了[鼓掌]
在上线之前，需要制作一个可视化网上管理后台 orz <del>因为那些管理的都比较傻</del>
### 我们需要你
- **急**招web前端开发者1-2名
  + 有经验者优先，需要较熟练的网页制作技术
  + 就是会写 html+css+js <del>当然会写 pug 或者 ejs 也是欢迎的</del>
- ios 程序员 <del>保护 OC/swift 程序员协会</del>
### 如何 <del>签订契约</del> 成为程序员
- <del>请登录你的 github 账号，并在本 issue 下回复 `${name} ${contact} ${position_to_apply}`</del>
- 也可以 <del>私戳</del> 联系 PKU Runner 公众号 _PKURunner_ 留下报名的信息

_**期待你的加入**_

## [Wiki页](https://github.com/pku-runner/pku-runner.github.io/wiki)
_<del>一脸懵逼的</del> 萌新可以看wiki页了解一下我们的项目 <del>的坑有多深</del>_

**Comment by owen8877** [comment]
Cheer!

**Comment by owen8877** [comment]
ceshiyixia?

**Comment by cnmozzie** [comment]
Name | Position to apply | Notes
------------ | ------------- | -------------
Guo Weixuan | web front end | just with some basic skills about web

**Comment by Baifly** [comment]
@cnmozzie 还是私戳一下微信号吧

**Comment by LukeXuan** [comment]
喝茶

**Comment by owen8877** [comment]
@LukeXuan Afraid...

**Comment by sentryjun** [comment]
射射发抖
