### ISSUE TITLE
与服务器通讯失败

### ISSUE THREAD

**Issue by MarshPop** [pku-runner/pku-runner.github.io#9]
Android端IAAA登陆时报错：
与PKU Runner 服务器通讯失败
java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

**Comment by taroxd** [comment]
下载新版本试试

**Comment by MarshPop** [comment]
问题解决（所以为什么只有PKU通知上的那个才是0.9.12版...）

**Comment by owen8877** [comment]
@MarshPop 请问能贴一下有问题的客户端版本和下载地址吗？我不是很清楚问题出在哪里了。

**Comment by MarshPop** [comment]
* https://github.com/pku-runner/pku-runner.github.io/blob/android/README.md
这里的下载地址是（ http://162.105.205.61:10201/public/apks/pkurunner-latest.apk ）
版本是0.9.11，会报错；
* http://pe.pku.edu.cn/info/1028/7192.htm
这里的下载地址是（ http://162.105.209.59/public/apks/pkurunner-latest.apk ）
版本是0.9.12；
* 然后好像其他应用市场（比如Coolapk）上的都是0.9.11

**Comment by owen8877** [comment]
@MarshPop 谢谢指出，我们立即更新
